# ============================================================
# Appium Server Configuration
# ============================================================
appium.server.url=http://127.0.0.1:4723
appium.server.port=4723

# ============================================================
# Device Configuration
# ============================================================
platform.name=Android
    # adb shell getprop ro.build.version.release (To get the platform version)
platform.version=14
    #adb shell getprop ro.product.model (to get the device name)
device.name=Pixel_9_Pro
device.udid=emulator-5554

# ============================================================
# App Configuration
# ============================================================
# automation.name: UiAutomator2 for Android, XCUITest for iOS
automation.name=UiAutomator2
auto.grant.permissions=true
no.reset=true
new.command.timeout=60

# ============================================================
# Timeouts (seconds)
# ============================================================
implicit.wait=10
explicit.wait=20
page.load.timeout=30

# ============================================================
# Report & Screenshot Paths
# ============================================================
screenshot.path=screenshots/
report.path=reports/
report.name=MobileAutomationReport

# ============================================================
# App Packages (extend for more apps)
# ============================================================
youtube.package=com.google.android.youtube
youtube.activity=com.google.android.youtube.app.honeycomb.Shell$HomeActivity

# ============================================================
# Search Configuration
# ============================================================
youtube.search.keyword=Google Launch Event
